spring.application.name=game

# Render dynamically assigns a port
server.port=${PORT:8080}

# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

# SendGrid Configuration
# Username epudu 'apikey' (literal string) gaane undali
spring.mail.host=smtp.sendgrid.net
spring.mail.port=587
spring.mail.username=apikey
spring.mail.password=${SENDGRID_API_KEY}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Verified Sender Email (Nuvvu kotha domain thone pampali)
# Render lo MAIL_SENDER = otp@vinayravula.online ani set chey
mail.from.email=${MAIL_SENDER}

# Logging & JWT
logging.level.com.example.demo=DEBUG
jwt.secret=${JWT_SECRET}

# Database Pooling
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
